nome = str(input('Digite o seu nome: ')).strip()
print('Analisando seu nome...')
print('Seu nome em maiúsculo é', nome.upper())
print('Seu nome em minúsculo é', nome.lower())
print(f'Seu nome tem ao todo', len(nome))
separa = nome.split()
print(f'Seu primeiro nome é {separa[0]} e ele tem {len(separa[0])} letras')